### ISSUE TITLE
NullPointerException in README's example

### ISSUE THREAD

**Issue by herrBez** [eth-sri/securify#21]
I think that the issue is the correlated to #19, but probably it is the same.

I have a NullPointerException when I run the example README's example:
```sh
java -jar build/libs/securify-0.1.jar -fh src/test/resources/solidity/transaction-reordering.bin.hex
```
> [Ljava.lang.StackTraceElement;@32d2fa64
FAILURE
Exception in thread "main" java.lang.NullPointerException
        at ch.securify.analysis.Dataflow.dispose(Dataflow.java:43)
        at ch.securify.Main.checkPatterns(Main.java:416)
        at ch.securify.Main.processHexFile(Main.java:151)
        at ch.securify.Main.main(Main.java:201)

I am running securify on Linux and with Java:
> openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

**Comment by hiqua** [comment]
Do you have Soufflé installed?

**Comment by herrBez** [comment]
I installed Soufflè and it works fine. Sorry for the waste of time
